# Generated by Django 3.2.12 on 2022-06-30 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_prestamos_nombre_libro_prestado'),
    ]

    operations = [
        migrations.CreateModel(
            name='prestatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('libro_prestado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libros')),
            ],
        ),
        migrations.DeleteModel(
            name='personal',
        ),
        migrations.RemoveField(
            model_name='prestamos',
            name='nombre_prestario',
        ),
        migrations.AddField(
            model_name='prestamos',
            name='nombre_prestatario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.prestatario'),
        ),
    ]
