# Generated by Django 3.2.12 on 2022-07-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_auto_20220630_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libros',
            old_name='editorial',
            new_name='nombre_libro',
        ),
        migrations.RemoveField(
            model_name='libros',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='prestatario',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='prestatario',
            name='libro_prestado',
        ),
        migrations.RemoveField(
            model_name='prestatario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='libros',
            name='is_prestado',
            field=models.BooleanField(default=False),
        ),
    ]
