# Generated by Django 3.2.12 on 2022-07-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_auto_20220703_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestatario',
            name='libros_prestados',
            field=models.ManyToManyField(through='biblioteca.Prestamos', to='biblioteca.Libros'),
        ),
        migrations.AddField(
            model_name='prestatario',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
