# Generated by Django 3.2.12 on 2022-06-27 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelav1', '0002_auto_20220626_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumnos',
            name='materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='escuelav1.materias'),
        ),
    ]
