# Generated by Django 3.2.12 on 2022-07-03 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escuelav1', '0004_auto_20220627_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumnos',
            old_name='boleta',
            new_name='boleta_alumno',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='apellido',
            new_name='email_alumno',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='materia',
            new_name='materia_cursada',
        ),
        migrations.RenameField(
            model_name='alumnos',
            old_name='email',
            new_name='nombre_alumno',
        ),
        migrations.RemoveField(
            model_name='alumnos',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='materias',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='materia_impartida',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='nombre',
        ),
        migrations.AddField(
            model_name='alumnos',
            name='profesor_asignado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='escuelav1.profesores'),
        ),
        migrations.AddField(
            model_name='materias',
            name='materia',
            field=models.CharField(blank=True, choices=[('EC', 'Economia'), ('PO', 'Programacion'), ('BD', 'Base de datos'), ('CI', 'Ciencias'), ('IA', 'Inteligencia artificial'), ('HU', 'Humanidades')], max_length=100),
        ),
    ]
