# Generated by Django 3.2.12 on 2022-07-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelav1', '0006_auto_20220703_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesores',
            name='materias_impartidas',
            field=models.ManyToManyField(through='escuelav1.Alumnos', to='escuelav1.Materias'),
        ),
    ]
