# Generated by Django 3.2.12 on 2022-07-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelav1', '0007_alter_profesores_materias_impartidas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materias',
            name='materia',
            field=models.CharField(blank=True, choices=[('EC', 'Economia'), ('PO', 'Programacion'), ('BD', 'Base de datos'), ('FI', 'Fisica'), ('IA', 'Inteligencia artificial'), ('QI', 'Quimica')], max_length=100),
        ),
        migrations.AlterField(
            model_name='profesores',
            name='materias_impartidas',
            field=models.ManyToManyField(through='escuelav1.Alumnos', to='escuelav1.Materias'),
        ),
    ]
