# Generated by Django 3.2.12 on 2022-07-03 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escuelav1', '0008_auto_20220703_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesores',
            name='apellido_profesor',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='email_profesor',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='materias_impartidas',
        ),
        migrations.RemoveField(
            model_name='profesores',
            name='nombre_profesor',
        ),
    ]
